### ISSUE TITLE
The notebook Sedona_OvertureMaps_Parquet_To_GeoParquet is not working in Docker

### ISSUE THREAD

**Issue by guillermodangelo** [wherobots/OvertureMaps#2]
The third cell of the notebook fails, because the object *spark* is not defined.
NameError: name 'spark' is not defined

**Comment by jiayuasu** [comment]
@guillermodangelo This notebook is not supposed to be working in the Sedona Docker. This is a notebook we ran on AWS EMR Sedona which has `spark` defined.

**Comment by guillermodangelo** [comment]
Oh, my bad.
