### ISSUE TITLE
Data from Wherobots unavailable - 404 Not Found

### ISSUE THREAD

**Issue by nihar1024** [wherobots/OvertureMaps#3]
Thank you for producing a publicly available GeoParquet version of Overture data, which should be much faster to filter and process.

Unfortunately, I am unable to access the dataset hosted on Wherobots' S3 bucket. I've tried accessing datasets of multiple themes, but get a 404 every time.

Is there a temporary issue with the hosting? Or is the dataset no longer available to the public?

**Comment by jiayuasu** [comment]
@nihar1024  No, the data is still available and open on Wherobots bucket. Have you tried the Overture map notebook in Sedona docker image?

**Comment by nihar1024** [comment]
Ah my bad - looks like I was missing the `hive_partitioning` param while using DuckDB which led it to misinterpret the path.
