### ISSUE TITLE
Problem of running a jupyter lab file with the latest release of the docker image

### ISSUE THREAD

**Issue by PavlosDem99** [wherobots/OvertureMaps#5]
When I try to run the Sedona_OvertureMaps_GeoParquet.ipynb of the latest release of the docker image, I encounter this error. 

![image](https://github.com/wherobots/OvertureMaps/assets/95135614/20e8654c-1550-41fd-8391-c5e754bd0bb7)

**Comment by jiayuasu** [comment]
@PavlosDem99 We just fixed this issue. Please pull either `1.5.1` image or `latest` image. Thanks!

**Comment by PavlosDem99** [comment]
> @PavlosDem99 We just fixed this issue. Please pull either `1.5.1` image or `latest` image. Thanks!

I just try the latest release and it works perfectly. Thanks
